name: DAST trigger
on:
  push:
    branches: [ mydev ]
jobs:
  dast_security_scan:
    runs-on: ubuntu-latest 
    container:
    image: docker://wasptree/veracode-dast-scan
    steps:
    - name: DAST
      run: /bin/sh -c "veracode-dast-scan vid: '${{ secrets.VERACODE_API_ID }}' vkey: '${{ secrets.VERACODE_API_KEY }}' -scan MyGruyere"
