name: DAST trigger
on:
  push:
    branches: [ mydev ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  dast_security_scan:
    runs-on: wasptree/veracode-dast-scan
   
    steps:
    - name: DAST
     run: veracode-dast-scan vid: '${{ secrets.VERACODE_API_ID }}' vkey: '${{ secrets.VERACODE_API_KEY }}' -scan MyGruyere
