name: DAST trigger
on:
  push:
    branches: [ main ]
jobs:
  dast_security_scan:
    runs-on: ubuntu-latest 
    steps:
    - name: DAST
      shell: bash
      run: |
        wget https://gitlab.com/wasptree/veracode-dast-scan/-/archive/latest/veracode-dast-scan-latest.zip
        unzip veracode-dast-scan-latest.zip && cd veracode-dast-scan-latest
        python3 veracode_dast_scan.py -vid "${{secrets.VERACODE_API_ID}}" -vkey "${{secrets.VERACODE_API_KEY}}" -scan "My Gruyere"
